version: '{branch}-{build}'
build: off

platform:
  - x86
  - x64

environment:
  global:
    PYTHONUNBUFFERED: True
    PYTHONWARNINGS: 'ignore:::wheel.pep425tags:'
    PYTHONPATH: C:\testdir
    NUNIT: nunit-console
    CONDA_BLD: C:\conda
    CONDA_BLD_VERSION: 3.5

    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\ci\run_with_env.cmd'

  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.3
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6

init:
  # Prepare environment
  - mkdir C:\testdir

  # Set environment variables depending based on build cfg
  - set CONDA_PY=%PYTHON_VERSION:.=%
  - set CONDA_BLD_ARCH=%PLATFORM:x=%
  - set PYTHON=C:\PYTHON%PYTHON_VERSION:.=%
  - if %PLATFORM%==x86 (set CONDA_BLD_ARCH=32)
  - if %PLATFORM%==x86 (set NUNIT=%NUNIT%-x86)
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)

  # Shortcut path to executables. Mostly because of OpenCover
  - set PYTHON_EXE=%PYTHON%\python.exe
  - set NUNIT_EXE=.\packages\NUnit.Runners.2.6.2\tools\%NUNIT%.exe
  - set OPENCOVER_EXE=.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
  - set RUNTIME_DIR=.\src\runtime\bin\%PLATFORM%\ReleaseWin\
  - set CS_TESTS=.\src\embed_tests\bin\%PLATFORM%\ReleaseWin\Python.EmbeddingTest.dll

  # Prepend newly installed Python to the PATH of this build
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version, architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -c "import ctypes; print(ctypes.sizeof(ctypes.c_wchar))"

install:
  # install for wheels & coverage
  - pip install --upgrade pip wheel coverage codecov six

  # Install OpenCover. Can't put on packages.config; not Linux/Mono compatible
  - .\tools\nuget\nuget.exe install OpenCover -OutputDirectory packages

build_script:
  # build clean sdist & wheel with coverage of setup.py, install local wheel
  - coverage run setup.py sdist bdist_wheel

test_script:
  - pip install --no-index --find-links=.\dist\ pythonnet
  - ps: Copy-Item (Resolve-Path .\build\*\Python.Test.dll) C:\testdir

  # Run python tests with C# coverage
  - '%OPENCOVER_EXE% -register:user -searchdirs:%RUNTIME_DIR% -output:py.coverage -target:%PYTHON_EXE% -targetargs:src\tests\runtests.py -returntargetcode'

  # Run Embedded tests with C# coverage
  # Embedded tests disabled due to open issues
  # - '%OPENCOVER_EXE% -register:user -searchdirs:%RUNTIME_DIR% -output:cs.coverage -target:%NUNIT_EXE% -targetargs:%CS_TESTS% -returntargetcode'

  # Build conda-recipe on Pull Requests
  - ps: .\ci\appveyor_build_recipe.ps1

on_finish:
  # Upload coverage
  - codecov

artifacts:
  - path: dist\*
