version: '{branch}-{build}'
build: off

image:
  - Visual Studio 2017
  
platform:
  - x86
  - x64

environment:
  global:
    PYTHONUNBUFFERED: True
    PYTHONWARNINGS: 'ignore:::wheel.pep425tags:'
    CODECOV_ENV: PYTHON_VERSION, PLATFORM

  matrix:
    - PYTHON_VERSION: 2.7 
      BUILD_OPTS: --xplat
    - PYTHON_VERSION: 3.5
      BUILD_OPTS: --xplat
    - PYTHON_VERSION: 3.6
      BUILD_OPTS: --xplat
    - PYTHON_VERSION: 3.7
      BUILD_OPTS: --xplat
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7

matrix:
    allow_failures:
      - PYTHON_VERSION: 3.4
        BUILD_OPTS: --xplat
      - PYTHON_VERSION: 3.4

init:
  # Update Environment Variables based on matrix/platform
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)

  # Put desired Python version first in PATH
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install -U pip
  - pip install --upgrade -r requirements.txt --quiet

build_script:
  # Create clean `sdist`. Only used for releases
  - python setup.py --quiet sdist
  # Build `wheel`
  - python setup.py bdist_wheel %BUILD_OPTS%

test_script:
  - pip install --no-index --find-links=.\dist\ pythonnet
  - ps: .\ci\appveyor_run_tests.ps1
  - ps: .\ci\appveyor_build_recipe.ps1

artifacts:
  - path: dist\*
