name: GitHub Actions

on: [ pull_request, push ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: actions/setup-python@v2

      - name: Build wheel
        run: |
          pip install --quiet wheel
          python setup.py bdist_wheel
      
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
      
      - run: |
          dotnet publish -f netstandard2.0 -o tests/binaries/netstandard/ src/testing/
          dotnet publish -f net5.0 -o tests/binaries/netcore/ src/testing/

      - uses: actions/upload-artifact@v2
        with:
          name: python-tests
          path: tests/

  python-test:
    needs: build
    name: Test Embedding .NET in Python
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        platform: [x86, x64]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheel
          path: wheel

      - uses: actions/download-artifact@v2
        with:
          name: python-tests
          path: python-tests

      - name: Set Environment on macOS
        uses: maxim-lobanov/setup-xamarin@v1
        if: ${{ matrix.os == 'macos' }}
        with:
          mono-version: latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.platform }}
      
      - run: |
          pip install psutil pytest clr-loader
          pip install --no-index --find-links=wheel pythonnet

      - name: Python Tests (Mono)
        if: ${{ matrix.os != 'windows' }}
        run: pytest --runtime mono ./python-tests --precompiled

      - name: Python Tests (.NET Core)
        run: pytest --runtime netcore ./python-tests --precompiled

      - name: Python Tests (.NET Framework)
        if: ${{ matrix.os == 'windows' }}
        run: pytest --runtime netfx ./python-tests --precompiled