name: GitHub Actions

on: [ pull_request, push ]

jobs:
  build-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        python: [3.6, 3.7, 3.8, 3.9]
        shutdown_mode: [Normal, Soft]

    env:
      PYTHONNET_SHUTDOWN_MODE: ${{ matrix.SHUTDOWN_MODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install --upgrade -r requirements.txt

      - name: Build and Install
        run: |
          python setup.py configure
          pip install -v .

      - name: Python Tests
        run: pytest

      - name: Run Embedding tests
        run: dotnet test src/embed_tests/

      # TODO: Run perf tests
      # TODO: Run mono tests on Windows?
